### ISSUE TITLE
Message sent confirmation for invalid messages

### ISSUE THREAD

**Issue by hoonkai** [jtjacques/mturk-manage#2]
Hi

I've noticed that when an invalid message is sent, a confirmation is still generated. For instance, if an invalid user ID is used, a confirmation is still generated:

![screen shot 2018-05-11 at 12 08 57 am](https://user-images.githubusercontent.com/14197204/39873926-a78c21f8-54af-11e8-9c42-8037288c63de.png)

I guess this should be unexpected behaviour.

Thanks

**Comment by jtjacques** [comment]
This is a documented limitation of the system due to limitations in the Mechanical Turk API

https://github.com/jtjacques/mturk-manage#message-worker

[Mechanical Turk API : NotifyWorkers](https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_NotifyWorkersOperation.html)

**Comment by hoonkai** [comment]
Noted. Thanks.
